-- =============================================================================
-- V11: Bang wishlists - chuyen danh sach yeu thich tu trinh duyet ve server
-- =============================================================================
-- VAN DE: truoc migration nay wishlist KHONG ton tai trong database. No nam
-- hoan toan trong localStorage cua trinh duyet (Zustand + persist, key
-- "booking-wishlist-storage"). Ba hau qua:
--
--   1. Wishlist gan voi TRINH DUYET chu khong gan voi TAI KHOAN. Dang nhap tai
--      khoan khac tren cung may van thay wishlist cu; dang nhap cung tai khoan
--      tren may khac thi rong.
--   2. Store luu ban sao title/price/imageUrl tai thoi diem bam tim. Tour doi
--      gia thi wishlist van hien gia cu; tour bi xoa thi the van con nhung bam
--      vao la hong (anh vo, trang loi).
--   3. Khong nhat quan: gio hang (carts/cart_items) da la bang that co khoa
--      ngoai toi users, trong khi cung mot loai tinh nang thi wishlist lai nam
--      o client.
--
-- Bang nay chi luu THAM CHIEU (user_id, tour_id) - khong nhan ban title/price.
-- Nho vay du lieu hien thi luon lay tuoi tu bang tours: tour doi gia thi
-- wishlist hien gia moi, tour bi xoa thi khoa ngoai chan hoac loc bo.
--
-- Di kem: entity Wishlist, WishlistRepository, WishlistService,
-- WishlistController va viet lai useWishlistStore o frontend de goi API.
--
-- LUU Y: du lieu wishlist cu trong localStorage cua nguoi dung KHONG duoc
-- chuyen sang day. Chung tro toi cac tour da bi xoa nen khong con y nghia;
-- nguoi dung se bat dau lai voi danh sach rong.
-- =============================================================================

CREATE TABLE wishlists (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    tour_id    BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_wishlists_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_wishlists_tour FOREIGN KEY (tour_id) REFERENCES tours (id)
        ON DELETE CASCADE,

    -- Mot nguoi khong the thich cung mot tour hai lan. Rang buoc o database chu
    -- khong chi o code: hai request bam tim dong thoi van bi chan.
    CONSTRAINT uq_wishlists_user_tour UNIQUE (user_id, tour_id)
);

-- Truy van chinh: "lay wishlist cua toi", sap xep moi nhat truoc
CREATE INDEX idx_wishlists_user ON wishlists (user_id, created_at DESC);

-- Chieu nguoc lai, phuc vu thong ke "tour nay duoc bao nhieu nguoi thich"
CREATE INDEX idx_wishlists_tour ON wishlists (tour_id);
