-- =============================================================================
-- V12: Refresh token co xoay vong (rotation) va phat hien dung lai (reuse)
-- =============================================================================
-- VAN DE: truoc migration nay he thong chi co MOT loai token - access token JWT
-- song 24 gio, nam trong localStorage cua trinh duyet. Ba hau qua:
--
--   1. Cua so tan cong 24 gio. Token bi lo (XSS, log, chia se man hinh) la ke
--      tan cong dung duoc tron mot ngay. Khong co cach nao rut ngan.
--   2. Khong the thu hoi. Blacklist invalidated_tokens chi ghi nhan token ma
--      chinh nguoi dung bam logout - dung ke trom thi khong ai bam gi ca.
--   3. Khong co dau vet. He thong khong bao gio biet mot token da bi sao chep.
--
-- GIAI PHAP: tach doi vai tro.
--   - Access token JWT rut xuong 15 phut, van stateless.
--   - Refresh token 30 ngay, la chuoi ngau nhien 256-bit (KHONG phai JWT) nen
--     bat buoc phai tra bang nay moi lan dung -> co cho de cuong che luat.
--
-- LUAT: MOI REFRESH TOKEN CHI DUNG DUOC MOT LAN.
-- Moi lan lam moi, token cu bi danh dau used_at + revoked_reason='ROTATED' va
-- mot token moi duoc sinh ra trong CUNG family_id.
--
-- PHAT HIEN DUNG LAI: neu mot token da co used_at (hoac da bi thu hoi) lai
-- xuat hien lan nua thi no DA BI SAO CHEP - server khong co cach nao phan biet
-- chu that voi ke trom, nen thu hoi TOAN BO family va gui email canh bao. Ca
-- hai ben phai dang nhap lai; ke trom mat quyen, chu that biet chuyen gi xay ra.
--
-- HAN 30 NGAY LA TUYET DOI, tinh tu luc dang nhap: moi token trong cung mot
-- family deu mang chung mot expires_at, xoay vong KHONG gia han them. Nho vay
-- mot phien khong the song mai chi vi nguoi dung online lien tuc, va viec don
-- dep het han xoa gon ca family mot luot.
-- =============================================================================

CREATE TABLE refresh_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- SHA-256 dang hex cua token, LUON 64 ky tu. Khong luu ban goc: lo ban sao
    -- database cung khong lay duoc token con hieu luc (cung ly do nhu V7).
    token_hash     VARCHAR(64)  NOT NULL,

    user_id        BIGINT       NOT NULL,

    -- Mot lan dang nhap = mot family. Toan bo chuoi token xoay vong tu lan dang
    -- nhap do deu mang chung gia tri nay - la don vi bi thu hoi khi phat hien
    -- dung lai.
    family_id      UUID         NOT NULL,

    -- Token da sinh ra token nay. Chi phuc vu truy vet: tu mot token bi lam
    -- dung co the lan nguoc ca chuoi. ON DELETE SET NULL de viec don dep khong
    -- bao gio bi khoa ngoai chan.
    parent_id      BIGINT,

    issued_at      TIMESTAMPTZ  NOT NULL,
    expires_at     TIMESTAMPTZ  NOT NULL,

    -- != NULL nghia la token DA TIEU. Xuat hien lan hai = bi sao chep.
    used_at        TIMESTAMPTZ,

    revoked_at     TIMESTAMPTZ,
    -- ROTATED | LOGOUT | REUSE_DETECTED | PASSWORD_RESET
    revoked_reason VARCHAR(30),

    -- Doc trong email canh bao de nguoi dung tu doi chieu "co phai minh khong"
    ip_address     VARCHAR(45),
    user_agent     VARCHAR(255),

    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user   FOREIGN KEY (user_id)   REFERENCES users (id),
    CONSTRAINT fk_refresh_tokens_parent FOREIGN KEY (parent_id) REFERENCES refresh_tokens (id)
        ON DELETE SET NULL
);

-- Thu hoi ca family khi phat hien dung lai, va khi logout
CREATE INDEX idx_refresh_tokens_family ON refresh_tokens (family_id);

-- Thu hoi moi phien cua mot nguoi (doi mat khau)
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

-- TokenCleanupScheduler quet theo cot nay
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens (expires_at);

-- =============================================================================
-- Bo blacklist access token
-- =============================================================================
-- Bang invalidated_tokens ton mot query o MOI request da xac thuc, doi lay viec
-- vo hieu hoa access token ngay khi logout. Voi access token song 24 gio thi
-- danh doi do dang gia. Voi 15 phut thi khong: logout gio thu hoi ca family
-- refresh token (ke trom khong lam moi duoc nua), con access token cu tu chet
-- trong toi da 15 phut. Doi lai moi request tren toan he thong bot mot query.
-- =============================================================================

DROP TABLE IF EXISTS invalidated_tokens;
